### ISSUE TITLE
Support TS 2.0 "nullable" types

### ISSUE THREAD

**Issue by bashor** [bashor/ts2kt#20]
Declarations with "nullbale" types are in `types-2.0` branch of DefinitelyTyped

**Comment by epabst** [comment]
FWIW, it seems so strange in TypeScript that there is such a thing as optional, null, and undefined, and they are all different from each other!

**Comment by bashor** [comment]
I think optional (`?:T`) is the same as `T | undefined`, and they have `null` and `undefined` separately because JavaScript has.

**Comment by andy-ms** [comment]
TS supports many singleton values (`null`, `undefined`, `42`, `"foo"`). `undefined` is one of them, and is the default value for uninitialized variables / fields. (An uninitialized field is the same as a non-existent one.)

For the type `{ x: number | undefined }`, TypeScript won't let you omit `x`, while it will for `{ x?: number }`. But at runtime, `({}).x` and `({ x: undefined }).x` are both `undefined`.

```ts
let a: { x?: number };
a = {};
a = { x: 1 };
a = { x: undefined }; // Yes, this is allowed

let b: { x: number | undefined };
b = {}; // Error: `x` is required
b = { x: 1 };
b = { x: undefined };
```

**Comment by bashor** [comment]
@andy-ms, good point, thank You.

Well, probably for `{ x: number | undefined }` we must not generate default accessors.

**Comment by bashor** [comment]
BTW, I've switched to tsc 2.0.10
