### ISSUE TITLE
Unclear how to run tool

### ISSUE THREAD

**Issue by epabst** [bashor/ts2kt#8]
I followed the steps in the README, but I still don't have .kt files for rx.  How do I run this tool to actually convert ts to kt?  Please add these steps to the README.

**Comment by bashor** [comment]
Right now it can be achieved in some ways:
1. Run it with node.js:
`node out/production/ts2kt/ts2kt.js path/to/input.d.ts path/to/output.kt`
Note: the root of the project should be working dir.
2. Directly call `translateToFile_puj7f4$` from JS (`translateToFile` in code).
3. Create run configuration like shared `jq` and run it.

Sorry for the inconvenience, the project is not production ready yet.

**Comment by epabst** [comment]
Thank you for the guidance.  I have a problem though:  I have no
out/production/ts2kt/ts2kt.js.

Eric

**Comment by epabst** [comment]
Oh.  I figured out how to generate out/production/ts2kt/ts2kt.js in
IntelliJ.

**Comment by bashor** [comment]
Fixed by @epabst in #9
